# Generated by Django 5.2.8 on 2025-11-06 22:25

import django.db.models.deletion
import files.utils
import files.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecole', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.utils.get_file_path, validators=[files.validators.validate_file_size, files.validators.validate_file_extension], verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('document', 'Document'), ('spreadsheet', 'Tableur'), ('text', 'Texte'), ('other', 'Autre')], default='other', max_length=20)),
                ('file_size', models.IntegerField(verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ecole.ecole', verbose_name='École')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['ecole', '-uploaded_at'], name='files_file_ecole_i_afb7ee_idx'), models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx')],
            },
        ),
    ]
